trigger:
  branches:
    include:
      - serverless

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AWS-Credentials

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g serverless
    displayName: 'Install Serverless Framework'

  - script: |
      ls
      pwd
    displayName: 'List Contents and Current Directory'

  - script: |
      sls config credentials --provider aws --key $(AWS_ACCESS_KEY_ID) --secret $(AWS_SECRET_ACCESS_KEY)
      cd pause_infra
      sls deploy --stage $(Environment) --region $(AWSRegion)
    displayName: 'Deploy Serverless Application'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

