trigger:
  branches:
    include:
      - serverless

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AWS-Credentials

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g serverless
      npm ci
    displayName: 'Install Serverless Framework'

  - script: |
      sls deploy --stage $(Environment) --region $(AWSRegion)
    displayName: 'Deploy Serverless Application'

# Enforce sequential execution
strategy:
  parallel: 1
